In [1]:
import pandas as pd

In [2]:
file_path = "../data/interim/cleaned_online_retail.xlsx"
sales = pd.read_excel(file_path)
sales

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...,...
392687,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
392688,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
392689,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
392690,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
392691,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [3]:
sales.head()

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [10]:
sales["Year"] = sales["InvoiceDate"].dt.year
sales["Month"] = sales["InvoiceDate"].dt.month
sales["Day"] = sales["InvoiceDate"].dt.day
sales["Hour"] = sales["InvoiceDate"].dt.hour
sales["Dayofweek"] = sales["InvoiceDate"].dt.dayofweek
sales["DayName" ] = sales["InvoiceDate"].dt.day_name()
sales["MonthName"] = sales["InvoiceDate"].dt.month_name()

In [13]:
sales["Description"].head(10)

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
5           SET 7 BABUSHKA NESTING BOXES
6      GLASS STAR FROSTED T-LIGHT HOLDER
7                 HAND WARMER UNION JACK
8              HAND WARMER RED POLKA DOT
9          ASSORTED COLOUR BIRD ORNAMENT
Name: Description, dtype: str

In [15]:
sales["Description"].str.strip()
sales["Description"].str.upper()

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
392687            PACK OF 20 SPACEBOY NAPKINS
392688           CHILDREN'S APRON DOLLY GIRL
392689          CHILDRENS CUTLERY DOLLY GIRL
392690        CHILDRENS CUTLERY CIRCUS PARADE
392691          BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 392692, dtype: str

In [17]:
sales["Country"].str.strip()
sales["Country"].str.upper()

0         UNITED KINGDOM
1         UNITED KINGDOM
2         UNITED KINGDOM
3         UNITED KINGDOM
4         UNITED KINGDOM
               ...
392687            FRANCE
392688            FRANCE
392689            FRANCE
392690            FRANCE
392691            FRANCE
Name: Country, Length: 392692, dtype: str

In [23]:
sales["TotalAmount"] = sales["Quantity"] * sales["UnitPrice"]

In [29]:
print(sales.isna().sum())
print(sales.dtypes)
print(sales.shape)

Unnamed: 0     0
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Year           0
Month          0
Day            0
Hour           0
Dayofweek      0
DayName        0
MonthName      0
TotalAmount    0
dtype: int64
Unnamed: 0              int64
InvoiceNo               int64
StockCode              object
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              int64
Country                   str
Year                    int32
Month                   int32
Day                     int32
Hour                    int32
Dayofweek               int32
DayName                   str
MonthName                 str
TotalAmount           float64
dtype: object
(392692, 17)

In [38]:
sales = sales.drop(columns = ["TotalAmount"])

In [40]:
sales.to_excel("../data/interim/tranformaed_online_retail.xlsx", index = False)

In [41]:
sales

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour,Dayofweek,DayName,MonthName
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2010,12,1,8,2,Wednesday,December
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010,12,1,8,2,Wednesday,December
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,2010,12,1,8,2,Wednesday,December
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010,12,1,8,2,Wednesday,December
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010,12,1,8,2,Wednesday,December
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392687,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,2011,12,9,12,4,Friday,December
392688,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,2011,12,9,12,4,Friday,December
392689,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,2011,12,9,12,4,Friday,December
392690,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,2011,12,9,12,4,Friday,December
392691,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,2011,12,9,12,4,Friday,December